services:
  trackrelay:
    image: trackrelay:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackrelay
    restart: always
    ports:
      - 8080:8080
    environment:
      - PUBLIC_API_TOKEN=token
      - PUBLIC_FTP=100
      - PUBLIC_REFRESH_RATE=2.5
      - PUBLIC_WEIGHT=75
      - PUBLIC_ATHLETE=Athlete
